apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- maven/0.2-nautes/maven.yaml
- git-clone/0.7/git-clone.yaml
- kaniko/0.6/kaniko.yaml
- kubernetes-actions/0.2/kubernetes-actions.yaml
- git-cli/0.4/git-cli.yaml
patches:
- patch: |-
    - op: replace
      path: /kind
      value: ClusterTask
  target:
    kind: Task
